// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARDfSKEoeDsQOtmXEJUO58MHj82mH-DA8',
    appId: '1:164665874204:web:7bcc52699deebd61804cd9',
    messagingSenderId: '164665874204',
    projectId: 'task-manager-2026-8c733',
    authDomain: 'task-manager-2026-8c733.firebaseapp.com',
    storageBucket: 'task-manager-2026-8c733.firebasestorage.app',
    measurementId: 'G-GPC25VDH99',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByGhVqpa8rYZdoGwsEvEZefba2aqIyu80',
    appId: '1:164665874204:android:f38575edddefb1ea804cd9',
    messagingSenderId: '164665874204',
    projectId: 'task-manager-2026-8c733',
    storageBucket: 'task-manager-2026-8c733.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdAomezwb4FOueQsmWHOvgbK1fCZZk0zA',
    appId: '1:164665874204:ios:e3cebe12733793d2804cd9',
    messagingSenderId: '164665874204',
    projectId: 'task-manager-2026-8c733',
    storageBucket: 'task-manager-2026-8c733.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdAomezwb4FOueQsmWHOvgbK1fCZZk0zA',
    appId: '1:164665874204:ios:e3cebe12733793d2804cd9',
    messagingSenderId: '164665874204',
    projectId: 'task-manager-2026-8c733',
    storageBucket: 'task-manager-2026-8c733.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARDfSKEoeDsQOtmXEJUO58MHj82mH-DA8',
    appId: '1:164665874204:web:8b7825282485161d804cd9',
    messagingSenderId: '164665874204',
    projectId: 'task-manager-2026-8c733',
    authDomain: 'task-manager-2026-8c733.firebaseapp.com',
    storageBucket: 'task-manager-2026-8c733.firebasestorage.app',
    measurementId: 'G-1D7MFM3NN4',
  );
}
